# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.configurationLimit = 5;
  boot.loader.efi.efiSysMountPoint = "/boot/esp";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0f269a72-0099-4dce-8f1c-828a808ed523";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0f269a72-0099-4dce-8f1c-828a808ed523";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "ssd"
    ];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-uuid/0f269a72-0099-4dce-8f1c-828a808ed523";
    fsType = "btrfs";
    options = [
      "subvol=persistent"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0f269a72-0099-4dce-8f1c-828a808ed523";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/boot/esp" = {
    device = "/dev/disk/by-uuid/1B3C-C1B6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
