user:
    nico:
        password: ENC[AES256_GCM,data:Rta3aDA=,iv:G0QtS5HSOxOQq1C/NZszplluWyH0sNDYTWJldosTdK8=,tag:Ht0nq/X2jxET7jwFD7pFIg==,type:str]
        password_hash: ENC[AES256_GCM,data:AVhSs+3M8V7oCiGhZAH6teLSKZ4FXBgOcfz38kBKLM8O4Mb8CuoTFX9TCQb7xLFy/DYQBZVa6qVKbvg2QLjPm+lHLuWrG1DWZO3PQ1D1nwI/StNUHJqP3rjXkvfLxazHBU+Q7+b0Sn9Baw==,iv:VrKua5nMq2CtQSBhOHrKsqj+//JibHNrkmghGP3/KE0=,tag:rwOKzoqEDGuVKLfRVYsIWA==,type:str]
        password_long: ENC[AES256_GCM,data:dIa8cNh/72ICfHJbwQ==,iv:P7UaBJiR/CRXkFaKqK2Lsun/SP8XWssKW6vtqFwxKLs=,tag:PZrTT7e3l5izVmHt3fAHUQ==,type:str]
services:
    botify:
        token: ENC[AES256_GCM,data:We6s4zksPGN8H3dvurYFyEWYheCUSd42Tq5fghRCPPTHE920YF5A3MwpyNHFiM9KXBiwucpAdCM8BDSD6KPT6gp41V2esFqr,iv:D4+9zU+a1eEx1ypuf6q9GpdGTQ/CQLBxdNKy4CKvFX4=,tag:8h2+4+48E4/mj91LFyVFoA==,type:str]
        openai_api_key: ENC[AES256_GCM,data:DgT31Amnxg2hs8NHv0RJb1H+A4/rWgSNGYgkS3IZr7Ejin8MXwb54QHEkKVwTocnBp6kbHK7X0yppUf8k10dEWz3GOqOCMz1sgsr3P3LeQA1q37aCT3q2ErTB5fbaAZfCWeg+oa5Qdx+8IGabK5VuKKGAVq2BHJGsDstrSaEsY4JVksMPX907J0OoxegxjmUFFeEIHrsSEExhzJlyfu/IZRgltI=,iv:47EOlqze6t0IYXMfgYdDBzqD0Cp7N5WGpOHMebHiIPQ=,tag:+nURSmzoAo0NSBPPII3b1g==,type:str]
wireguard:
    pubkey: ENC[AES256_GCM,data:nciRLYEk4os1E1TU4+txJfEi7hH/TsjzLVQgTqHZEEcDSTVmH9VNo7Vw38M=,iv:a/yuQQFmyssfML8UtV4QEFdNmQJUH0h+47zhTCd2shk=,tag:CbMotzVAUhj02b0MXvb0tw==,type:str]
    privkey: ENC[AES256_GCM,data:t4A0NAIx5FUgJly4/EhPG04Rn1qaCT4/FhTExvtb74Es9YwRTrytR5qAw+k=,iv:YDbMlUIvYnh6ClRUD69B1GuTjCXTafNT96I3auWgY9k=,tag:/nErrtRMJPYdsr7PVZSbRg==,type:str]
cloudflare:
    api_token: ENC[AES256_GCM,data:NAywwu4qHfec/kIsPwF2RPObgszxo7VLtsw4is1ES1CL4SSUdMt3Bg==,iv:zWRVv44nP3fYwEQu5P5XmlqA3BqFC0cysqaPHU9wVk4=,tag:5Wf48r9s70WQg7/pQcp0VQ==,type:str]
crowdsec:
    enrollment_key: ENC[AES256_GCM,data:Z3RbpbIC9qAzZksEJHhODx06bWK0z9qQpA==,iv:QtGQLLEkUWsLUlYHIKXgYq4rtW3WCOGOV2uwQerg90w=,tag:3/AT+DB9iDlhnMvJ654gfQ==,type:str]
restic:
    password: ENC[AES256_GCM,data:EWRMnXp877onsrHF/A==,iv:iybPEiGg+Pu3P6ULNy/QL1yHlppukKFW7DGZ1Iy/DbY=,tag:WDsRdgOV+xYy9xiYVMF5Cw==,type:str]
    repository: ENC[AES256_GCM,data:auZymSuZ1f25ZL0h7ikYl8QdSW5ymtmSUmO/2/gZdjeoJFkfCwMm237FnZKI/oeq,iv:4nYvJq+d0/L0YmYJGbiEVKtG1alGmb5xlLBU2C+YijU=,tag:aG1GqWr5NuZZ+EJcb12Nyg==,type:str]
glance:
    pihole_password: ENC[AES256_GCM,data:aQXZkUmkFP0DvGh8bSF82hpNQV0ZLpGovhKgJ49pfleNWh4FY8ZEY2jK7bc=,iv:yJhv1z64xycoSGZuAhrSSgZfipyFqaMlAtMlqb5zZGU=,tag:B7QvaKJH09tLZ7+hmiYm6A==,type:str]
    immich_api_key: ENC[AES256_GCM,data:9rsRdEGLZuZu91iefGuVM+FnkTYC0oH+nrHzpkNQYT74hKkSabnFmKk=,iv:MuAqS1kucKcHMqpXkWfFk6uH3L9zO4trBfTTyfZqSe4=,tag:0ZoGFwUgnwH/dHB0Gg07IA==,type:str]
    3d_printer_remote: ENC[AES256_GCM,data:9N3+zz6Sh2oyC5XcBBholduT+tohuUpq0jkr4vl5Bv8=,iv:h4HLDDCRtnSHH6ypzflQ2MYN6j8PJQ8e1wGb3/f43Tw=,tag:11UxcPjpsxqLBkKoHDT6/w==,type:str]
    vps_remote: ENC[AES256_GCM,data:+u6NFUbpqcl0VjTsWUvvXUry6zLkuo6oKFUrNtq/vWk=,iv:wkLwhF33nhgozqy0r6lyjPYxoOfnrSBMQqcqVj2GWdI=,tag:PpodKBVELceKQbOgwjKNOQ==,type:str]
glance_restic:
    password: ENC[AES256_GCM,data:BjP76hsvqpyrL9/f4ZsysJ7v+3xCbtBSFegwIbL4Ki+FSOpNCg==,iv:APhp40sV6uEEGBk/iOHgEfqGmzdJKFSqNf0S3dJNH4Y=,tag:cnSDxHIlwePqoKAlc+0uUg==,type:str]
    url: ENC[AES256_GCM,data:vRm4imJrxK9ZjGlZEzcvnZH0PhZY/uU3O3IN5/2MIJKAd6lRngCY+GQgRhwonAosfOdbFLhJ31GifAaarPvonSs1sA==,iv:AGxV3kT04Ya3Lp0n0KMUIpgkOOt58oL1GMoOJVG56+Y=,tag:79Zn12nNJS751f0nm+UBsw==,type:str]
homeassistant:
    url: ENC[AES256_GCM,data:UzVjoTskmXVcXx4Em1Qnn0v99tCSzWhM,iv:W6DCT52IQRXZrCpgLw4j7MGu8ug2jTAR8HvWLV8t+Y4=,tag:+i64fJYfF3XHPde96i5CEw==,type:str]
    token: ENC[AES256_GCM,data:IVTGIu9t3TSa7K2nRbAje+qRRz3C/7Si3EmEu+FGWxNhFqXegd8KZ9vKCnulLkP2U4Zf9fciOGQHu4zqAYp7UIfm8IeYsdTe9eInqRlqAjDKY57dtQU40S4RGl/0H5axkq2v/k1fnspWyMp7kJSoAysVVCDzVANA1UjnSvO8DRbnGVlpmNbJVXA4ADHyhxg7Ov09qDugBkVZAMNETl3LtixK56NUENyPNYK83Q7HWqG5+PvguR9x,iv:0QvC6A7RliaEe3YBlVRn5kb2IsmYPAGMf0SD68WnFI8=,tag:bty4IuyugFhgA73vL/Tdtw==,type:str]
google:
    calendar:
        client_id: ENC[AES256_GCM,data:bpvLAN5OLvd77EOow0ghiYg8RvdUWYAqKr5gqDyKAKG2qtzpwQA1uc/NT+2uuWPWdDQ9sL8Vi5AGFqMSkREumOfX7SGDPSLR,iv:P5PqRYqf/dBEbD7tQADWlqTA72IV5hqiEXinGaL0w6k=,tag:x4vWiZf0zV3W0C8yie1Afw==,type:str]
        client_secret: ENC[AES256_GCM,data:bMJg7rjcJT/u22Oo9W07uR37NuOXCJgJT9Gg6X0bv/3eqpI=,iv:tBvkVSxixsAFkqhTi/VLhNhfI9hLT54j0/xqpuySpq0=,tag:jWQxrWWMRW7iz78aWiMaOQ==,type:str]
openai:
    api_key: ENC[AES256_GCM,data:waBfQULRWpd01G0S3J0YbTzYRssecgNAytYzZlF/dn1BXnwoV0mXh5/U6ttMFazl99DRt0UdlsMgsm6d4wO1zpEBGkFe9+6ruu4PTD+B3yjCZaps43aCl7RKSo5M8B+uzPXSVtBaX6xD4HDpN9VO0veGYUcc9rHN4Zbx0HedFYlPtX4BZxz4SCW5tCMrZ6dnyfKTUfJrinpmDpowi780uOOZpYk=,iv:3JGypRnDtEz9wT0pcddCAfDPAtXKU3jzUrf51Hg/Z9A=,tag:BAXMs6sFev6QBCv4XIXcyw==,type:str]
sops:
    age:
        - recipient: age1sxx4vd5awn5g8t5jxlcgafc56c9twa9l6ty7rddq753afhxh4cuqc4n2nu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNVFDVU1xYlpuYVI5L0JU
            VUkyUmN6SVJQR25lWCt1MHlTbENjRUl0eXhZCkp2dGlReUhMaElENVAvNjl5TVlM
            T3dXWXZHbmRXa1JnV1o4VmVIYzdLcXMKLS0tIEdsSnlhYkZ1WGdnOHVnNjdma1Rl
            UzgzU09xcnd3ZWQzOGNManRaYjFrOFEKU+73BPHohKypmBoaASUjZjDXtkjzh90w
            eCkqwF/px2Cz9wuYbLhTWZLoQCOiQo//rdnWQUvzS3FXDln3fXjRoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T18:06:21Z"
    mac: ENC[AES256_GCM,data:WFQ3VaCsASGWr1G+LzfulPYA9JT1oC81LNWJoBGe+eJbiTnKi2/1l4od79a6srSb4KcImdbvY0LSk8m/T+ofxfY1vSKoa0OTkXLzxORN4XHo00J2gq9ZSpMxjfbElaVtE9jd90CN0HdhvWCne5Ey4Ye+lnEEmY3o3ztoj5cOBFo=,iv:w0dfl6i+Bt8IanxJf+kOthIiycoMHb7NDZ69DUDqexg=,tag:KyzB09zYxA+Fr3cLXafVlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
